name: Deployment
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    environment: AWS-EC2
    needs: phpunit
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} > ~/.ssh/known_hosts
          
      - name: Connect, Checkout, Pull
        run: |
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "cd ${{ secrets.DEPLOY_PATH }} && git checkout main && git pull && exit"
          
      - name: Clean keys
        run: rm -rf ~/.ssh
