name: Run PHPUnit Tests

on:
  push:
    branches:
      - dev
      - tests
      - features/**
  pull_request:
    branches:
      - main

jobs:
  phpunit:
    name: PHPUnit Tests & Coverage
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.result.outputs.result }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: ctype, dom, json, libxml, mbstring, pdo, phar, sqlite3, tokenizer, xml, xmlwriter
          tools: composer, phpunit, phpstan

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit tests

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: DanielADK/tul-stin
